name: Deploy Express API
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Decode SSH key
        run: |
          echo "${{ secrets.TRACKIFY_DEMO_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            git clone https://github.com/${{ github.repository }} demo && cd demo
            git pull origin master
            npm ci
            pm2 restart express-api || pm2 start app.js --name express-api
          EOF
